### ISSUE TITLE
Getting an error in verifyAndDecodeNotification method

### ISSUE THREAD

**Issue by Arshadshaykh** [apple/app-store-server-library-node#176]
I am trying to verify and decode notification with **verifyAndDecodeNotification** method And I am getting **status: 1 VERIFICATION_FAILURE,**

this was the error stack

at SignedDataVerifier.verifyCertificateChain (/rater-qa/node_modules/@apple/app-store-server-library/dist/jws_verification.js:217:19)
at SignedDataVerifier.verifyJWT (/rater-qa/node_modules/@apple/app-store-server-library/dist/jws_verification.js:181:42)
at SignedDataVerifier.verifyAndDecodeNotification (/rater-qa/node_modules/@apple/app-store-server-library/dist/jws_verification.js:97:39)

**Comment by alexanderjordanbaker** [comment]
That would be expected if the certificate was not from Apple. Could you paste the contents of the x5c header chain here? And to confirm, these are not Xcode transactions, but Sandbox or Production transactions?

**Comment by Arshadshaykh** [comment]
Thanks for the reply @alexanderjordanbaker but the issue is solved the buffer which I was passing was not correct.

**Comment by Arshadshaykh** [comment]
I'm unsure whether I should implement the backend logic for updating transactions within the same API that App Store Connect uses to send notifications. Could you clarify the process?

**Comment by alexanderjordanbaker** [comment]
@Arshadshaykh are you talking about App Store Server Notifications? App Store Connect is used for managing products, not transaction data?
