### ISSUE TITLE
Running client. requestTestNotification () reported error 401

### ISSUE THREAD

**Issue by fhtwl** [apple/app-store-server-library-node#221]
```ts
import { AppStoreServerAPIClient, Environment, SendTestNotificationResponse } from "@apple/app-store-server-library"

const issuerId = "99b16628-15e4-4668-972b-eeff55eeff55"
const keyId = "ABCDEFGHIJ"
const bundleId = "com.example"
const filePath = "/path/to/key/SubscriptionKey_ABCDEFGHIJ.p8"
const encodedKey = readFile(filePath) // Specific implementation may vary
const environment = Environment.SANDBOX

const client = new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, environment)

try {
    const response: SendTestNotificationResponse = await client.requestTestNotification()
    console.log(response)
} catch (e) {
    console.error(e)
}
```

```
APIException [Error]: 
    at AppStoreServerAPIClient.makeRequest (F:\code\github\nest\gamgpt-service\node_modules\.pnpm\@apple+app-store-server-library@1.4.0\node_modules\@apple\app-store-server-library\index.ts:172:19)    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppStoreServerAPIClient.requestTestNotification (F:\code\github\nest\gamgpt-service\node_modules\.pnpm\@apple+app-store-server-library@1.4.0\node_modules\@apple\app-store-server-library\index.ts:361:16)
    at IosAppPayService.test (F:\code\github\nest\gamgpt-service\src\modules\app-web\payment-order\ios-app-pay.service.ts:234:9) {
  httpStatusCode: 401,
  apiError: null,
  errorMessage: null
}

```

**Comment by Daavidaviid** [comment]
What was the issue? I get the same error
