### ISSUE TITLE
VerificationException Prod Webhook

### ISSUE THREAD

**Issue by aslamanver** [apple/app-store-server-library-node#30]
```
{"severity":"ERROR","message":"webhook_apple VerificationException [Error]\n    at SignedDataVerifier.verifyAndDecodeNotification (/Users/aslam/Desktop/projects/cf/functions/node_modules/@apple/app-store-server-library/dist/jwt_verification.js:90:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /Users/aslam/Desktop/projects/cf/functions/lib/src/app/app.js:610:42 {\n  status: 2,\n  cause: undefined\n}"}
```

**Comment by alexanderjordanbaker** [comment]
Please provide more information, the full stack trace, environment details, etc.

**Comment by alexanderjordanbaker** [comment]
Closing due to lack of information
