### ISSUE TITLE
verifyAndDecodeNotification throws VerificationException - cause is FetchError socket hang up

### ISSUE THREAD

**Issue by darvelo** [apple/app-store-server-library-node#47]
When using `verifier.verifyAndDecodeNotification(signedPayload)` from my local development server it throws this `VerificationException` when processing notification failures and I'm not sure why. I set `enableOnlineChecks = true`.

```
VerificationException Status error.status: 1
error.cause: FetchError: request to http://ocsp.apple.com/ocsp03-applerootcag3 failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/node/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketOnEnd (node:_http_client:519:9)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
error.message:
Notification failure process failure: VerificationException [Error]
    at SignedDataVerifier.verifyJWT (/home/node/app/node_modules/@apple/app-store-server-library/dist/jws_verification.js:163:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SignedDataVerifier.verifyAndDecodeNotification (/home/node/app/node_modules/@apple/app-store-server-library/dist/jws_verification.js:91:28)
    at async processNotificationSignedPayload (file:///[redacted].js:64:38)
    at async file:///[redacted].js:259:24
    at async Promise.all (index 5)
    at async Module.processNotificationFailures (file:///[redacted].js:256:46)
    at async processAppStoreNotificationFailures (file:///[redacted].js:20:9) {
  status: 1,
  cause: FetchError: request to http://ocsp.apple.com/ocsp03-applerootcag3 failed, reason: socket hang up
      at ClientRequest.<anonymous> (/home/node/app/node_modules/node-fetch/lib/index.js:1501:11)
      at ClientRequest.emit (node:events:514:28)
      at Socket.socketOnEnd (node:_http_client:519:9)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1589:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNRESET',
    code: 'ECONNRESET'
  }
}
```

I'm using the same root certs that I use on my staging server in the cloud, and this error isn't thrown there. Both the dev and staging servers use `Environment.SANDBOX`. I'm currently preparing a production launch in a few weeks so hoping this won't manifest on the production server as well.

I can confirm after installing `node-fetch` that I can make requests with it, so that leads me to believe it may have something to do with the Apple root certs.

EDIT: Maybe an `http://` vs. `https://` issue? https://stackoverflow.com/a/70664808/544252 Though my local dev server is definitely not using self-signed https certificates or any at all.

**Comment by alexanderjordanbaker** [comment]
This would indicate that you are unable to connect to the servers responsible for determining revocation. Do you have any outbound firewalls that might block this traffic?

**Comment by darvelo** [comment]
@alexanderjordanbaker Not that I can think of, the local dev server is able to fetch public webpages using HTTP or HTTPS and print the HTML to console successfully, including http://apple.com and https://apple.com

**Comment by darvelo** [comment]
I just set `enableOnlineChecks = ENVIRONMENT !== 'development'`, this solution should be fine for dev. Thank you!

**Comment by alexanderjordanbaker** [comment]
Note that this would only apply for locally generate certs used in like unit testing, certificates in the Sandbox environment should still have enableOnlineChecks true in most cases

**Comment by darvelo** [comment]
Good to note, thank you 🙏🏽  I'll try again when there's more time to see what's going on with it.
