### ISSUE TITLE
I get an error when trying to decrypt my signed payload

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [apple/app-store-server-library-node#71]
For more context it works whenever I send test notification locally
```js
  const client = this.client();
  const response: SendTestNotificationResponse = await client.requestTestNotification();
  const checkResponse = client.getTestNotificationStatus(response.testNotificationToken);
  return checkResponse;
```

**Comment by GoodnessEzeokafor** [comment]
But whenever I perform a transaction on my emulater, and pass the `localVerificationData` to my server, get my signed transaction and try to decode the jwt I get this
```
VerificationException [Error]: 
    at SignedDataVerifier.verifyAndDecodeNotification (/Users/goodnessezeokafor/development/bitmama/changera-api/node_modules/@apple/app-store-server-library/jws_verification.ts:109:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppleApiKeyUtils.verifyWebhookPayload (/Users/goodnessezeokafor/development/bitmama/changera-api/dist/apps/wallet-service/main.js:54330:42)
    at ApplePayWebhookServices.applePayWebhook (/Users/goodnessezeokafor/development/bitmama/changera-api/dist/apps/wallet-service/main.js:30342:30)
    at WebhookController.applePayWebhook (/Users/goodnessezeokafor/development/bitmama/changera-api/dist/apps/wallet-service/main.js:6641:30)
    at /Users/goodnessezeokafor/development/bitmama/changera-api/node_modules/@nestjs/microservices/context/rpc-proxy.js:11:32
    at ServerRMQ.handleEvent (/Users/goodnessezeokafor/development/bitmama/changera-api/node_modules/@nestjs/microservices/server/server.js:71:32) {
  status: 2,
  cause: undefined
}
```

**Comment by alexanderjordanbaker** [comment]
Are you using the xcode environment for the SignedDataVerifier?

**Comment by alexanderjordanbaker** [comment]
After looking more closely, this has status=2 which is VerificationStatus.INVALID_APP_IDENTIFIER. Make sure the appApple id and bundleId passed to the SignedDataVerifier match the app the transaction is for

**Comment by GoodnessEzeokafor** [comment]
I was @alexanderjordanbaker , sorry for the late reply
thanks so much for the help

**Comment by spookyuser** [comment]
For future googlers i also has this error and my issue was that i was using `verifyAndDecodeTransaction` instead of `verifyAndDecodeNotification`  - so if you're getting this and it looks like your `SignedDataVerifier(...)` is being constructed correctly, make sure you're using the correct method too!

**Comment by Arshadshaykh** [comment]
Hello there I am also trying to verify And Decode Notification And I am getting status: 1 VERIFICATION_FAILURE

**Comment by johnil** [comment]
Remind those who see this issue later that if you have configured APP_APPLE_ID in the env, make sure that the parameter type passed when initializing SignedDataVerifier is number instead of string; otherwise, it will return this exception.
