### ISSUE TITLE
Error: secretOrPrivateKey must be an asymmetric key when using ES256 in Production environment

### ISSUE THREAD

**Issue by thomas2109** [apple/app-store-server-library-node#79]
Everything works fine in the Sandbox environment. But when I switch to production, with the same private key and other variables, I got this error

>  error: Error: secretOrPrivateKey must be an asymmetric key when using ES256
    at Object.module.exports [as sign] (/opt/app/node_modules/@apple/app-store-server-library/node_modules/jsonwebtoken/sign.js:130:22)
    at AppStoreServerAPIClient.createBearerToken (/opt/app/node_modules/@apple/app-store-server-library/index.ts:365:29)
    at AppStoreServerAPIClient.makeRequest (/opt/app/node_modules/@apple/app-store-server-library/index.ts:111:47)
    at AppStoreServerAPIClient.getTransactionHistory (/opt/app/node_modules/@apple/app-store-server-library/index.ts:311:27)
    at findLastReceiptFromOriginalTransactionId (/opt/app/v1/helpers/appleHelpers.ts:386:49)

I found that it may be caused by the wrong format of the private key file or the newline character, but it still works in the Sandbox environment. I'm using `fs-extra` to read the p8 file

> const encodedKey = fs.readFileSync('apple-api-key.p8', { encoding: 'utf8' });
 
Node v16.19.0

**Comment by sailingwithsandeep** [comment]
Hey @thomas2109, i am unable to running it sandbox as well. Here's my code:
`const _filename = fileURLToPath(import.meta.url);
const _dirname = dirname(_filename);
const encodedKey = path.join(_dirname, `../../utils/lib/dir`, 'test.p8');
const client = new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, environment);
`
What am i doing wrong here?
Thanks!

**Comment by longhan2109** [comment]
It looks like you just only defined the path of the file. You need to read the content of the file also

**Comment by thomas2109** [comment]
It seems that you just only defined that path of the file. You need to read to content of the file to extract the key

**Comment by alexanderjordanbaker** [comment]
So Sandbox or Production doesn't affect the parsing at the p8, it is definitely possible if the format of the file was changed it could be throwing an error

**Comment by sailingwithsandeep** [comment]
> It seems that you just only defined that path of the file. You need to read to content of the file to extract the key

Oops. added the fs readFileSync now it's working thanks.

**Comment by alexanderjordanbaker** [comment]
@thomas2109 just to confirm the below logs one success and one error?
```
const client = new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, Environment.SANDBOX)
try {
    const response: SendTestNotificationResponse = await client.requestTestNotification()
    console.log("Success Sandbox")
} catch (e) {
    console.error(e)
}
const prodClient = new AppStoreServerAPIClient(encodedKey, keyId, issuerId, bundleId, Environment.PRODUCTION)
try {
    const response: SendTestNotificationResponse = await client.requestTestNotification()
    console.log("Success Production")
} catch (e) {
    console.error(e)
}
```

**Comment by thomas2109** [comment]
@alexanderjordanbaker  Both succeeded in my development environment.

**Comment by alexanderjordanbaker** [comment]
Oh, you don't mean Production as in `Environment.PRODUCTION` you mean your production environment, I'm tracking now. Yeah, it sounds like the formatting of the p8 file differs between the environments. I recommend checking the line endings and testing with the same OS as production to rule out any OS differences.

**Comment by alexanderjordanbaker** [comment]
@thomas2109 Were you able to resolve your issue?

**Comment by thomas2109** [comment]
@alexanderjordanbaker My task is pending for now. But I'm try to import the key as env variable instead of read from file. After some investigation, I think it may related to the `/n` character which cause the wrong format of key issue

**Comment by alexanderjordanbaker** [comment]
@thomas2109 If you have additional issues, please open a new issue, and we'll be happy to take a look. For now, closing this issue due to inactivity

**Comment by Adesh-Pandey** [comment]
@thomas2109, did it work? Using env variable instead? 
I m having similar where it's not working using the same key from the environment variable in sandbox environment. (Configured with ENVIRONMENT.SANDBOX)
It works fine on production. (Configured with ENVIRONMENT.PRODUCTION)
